name: CD Workflow

on:
  workflow_run:
    workflows: [CI Workflow]
    types:
      - completed
    # branches: [develop]


jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_ACCESS_TOKEN}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            
    - name: Build & Push Production Image
      run: |
        docker build --build-arg DB_URL=${{secrets.DB_URL}} -f ./backend/production/prod.Dockerfile -t ${{secrets.DOCKER_USERNAME}}/g4t1_sbrp:spm-prod ./backend
        docker push ${{secrets.DOCKER_USERNAME}}/g4t1_sbrp:spm-prod

    - name: Build & Push Test Image
      run: |
        docker build --build-arg TEST_DB_URL=${{secrets.TEST_DB_URL}} -f ./backend/test/test.Dockerfile -t ${{secrets.DOCKER_USERNAME}}/g4t1_sbrp:spm-test ./backend
        docker push ${{secrets.DOCKER_USERNAME}}/g4t1_sbrp:spm-test
    
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Create ~/.ssh directory
      run: mkdir -p ~/.ssh

    - name: Fetch custom known_hosts from Github Secret
      run: echo "${{ secrets. KNOWN_HOSTS_SECRET }}" > ~/.ssh/known_hosts

    - name: Set permissions for private key
      run: |
        echo: "${{ secrets.EC2_SSH_KEY }}" > g4t1_sbrp.pem
        chmod 400 g4t1_sbrp.pem