---
name: CI Workflow

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-ci-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build code
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r backend/requirements.txt

      - name: Test backend code using pytest
        run: pytest backend/tests

  build-and-push-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Build and Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          # Build Docker image
          docker build -t my-app .

          # Tag Docker image
          docker tag my-app chulintian/is212-g4t1

          # Authenticate with Docker Hub
          echo "$DOCKER_ACCESS_TOKEN" |
            docker login -u "$DOCKER_USERNAME" --password-stdin

          # Push the Docker image to Docker Hub
          docker push chulintian/is212-g4t1
