name: CI Workflow

on:
  # every time a new commit is pushed to PR, this workflow will run
  pull request:

# Ensure only a single job or workflow using the same concurrency group will run at a time
# When a concurrent job or workflow is queued, if another job or workflow is using the same concurrency group in the repository is in progress
# the queued job or workflow will be pending
concurrency:
  group: ${{ github.ref }}-ci-workflow # The branch or tag ref that triggered the workflow run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Install Dependencies
        run: npm install

      - name: Build code
        run: npm run serve

test:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install -r backend/requirements.txt 

    - name: Test backend code using pytest
      run: pytest backend/tests  

build-and-push-docker:
  needs: test
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Build and Push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: 
        # Build Docker image
        docker build -t my-app .

        # Tag Docker image
        docker tag my-app chulintian/is212-g4t1

        # Authenticate with Docker Hub
        echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

        # Push the Docker image to Docker Hub
        docker push chulintian/is212-g4t1